export const AUTH_LOGIN = "auth:login"
export const AUTH_REGISTER = "auth:register"
export const DOWNLOAD_PROGRESS = "download:progress"
export const DOWNLOAD_COMPLETE = "download:complete"
export const PLAY_ENTITY = "play:entity"
export const REFRESH_ENTITIES = "refresh:entities"
export const WEBSOCKET_MESSAGE = "websocket:message"
export const WEBSOCKET_OPEN = "websocket:open"
