export const REFRESH_ENTITIES = "refresh:entities"
export const DOWNLOAD_PROGRESS = "download:progress"
export const DOWNLOAD_COMPLETE = "download:complete"
export const WEBSOCKET_MESSAGE = "websocket:message"
export const WEBSOCKET_OPEN = "websocket:open"
